In [2]:
import pandas as pd

In [3]:
# Load Data from CSV
file_path = r"ADE_source_data.csv"
df = pd.read_csv(file_path)

In [8]:
df

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,1966,14,Chhattisgarh,Durg,548.00,185.00,337.59,44.00,20.00,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.00,409.00,747.71,50.00,26.00,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.30,468.00,841.27,53.70,30.00,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.40,400.80,711.40,49.40,26.50,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.60,473.60,828.55,44.20,29.00,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16141,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.00,0.0,0.0,0.0,0.00,9.02,9.03,0.48,0.08,0.00
16142,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.00,0.0,0.0,0.0,0.00,8.63,8.64,0.46,0.04,0.00
16143,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.00,0.0,0.0,0.0,0.00,6.84,6.85,0.42,0.01,0.00
16144,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.00,0.0,0.0,0.0,0.03,6.40,6.43,0.03,0.01,0.00
16145,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00

In [9]:
df.columns

Index(['Dist Code', 'Year', 'State Code', 'State Name', 'Dist Name',
       'RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)',
       'RICE YIELD (Kg per ha)', 'WHEAT AREA (1000 ha)',
       'WHEAT PRODUCTION (1000 tons)', 'WHEAT YIELD (Kg per ha)',
       'KHARIF SORGHUM AREA (1000 ha)',
       'KHARIF SORGHUM PRODUCTION (1000 tons)',
       'KHARIF SORGHUM YIELD (Kg per ha)', 'RABI SORGHUM AREA (1000 ha)',
       'RABI SORGHUM PRODUCTION (1000 tons)', 'RABI SORGHUM YIELD (Kg per ha)',
       'SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)',
       'SORGHUM YIELD (Kg per ha)', 'PEARL MILLET AREA (1000 ha)',
       'PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)',
       'MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)',
       'MAIZE YIELD (Kg per ha)', 'FINGER MILLET AREA (1000 ha)',
       'FINGER MILLET PRODUCTION (1000 tons)',
       'FINGER MILLET YIELD (Kg per ha)', 'BARLEY AREA (1000 ha)',
       'BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)',
       'CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)',
       'CHICKPEA YIELD (Kg per ha)', 'PIGEONPEA AREA (1000 ha)',
       'PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)',
       'MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)',
       'MINOR PULSES YIELD (Kg per ha)', 'GROUNDNUT AREA (1000 ha)',
       'GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)',
       'SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)',
       'SESAMUM YIELD (Kg per ha)', 'RAPESEED AND MUSTARD AREA (1000 ha)',
       'RAPESEED AND MUSTARD PRODUCTION (1000 tons)',
       'RAPESEED AND MUSTARD YIELD (Kg per ha)', 'SAFFLOWER AREA (1000 ha)',
       'SAFFLOWER PRODUCTION (1000 tons)', 'SAFFLOWER YIELD (Kg per ha)',
       'CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)',
       'CASTOR YIELD (Kg per ha)', 'LINSEED AREA (1000 ha)',
       'LINSEED PRODUCTION (1000 tons)', 'LINSEED YIELD (Kg per ha)',
       'SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)',
       'SUNFLOWER YIELD (Kg per ha)', 'SOYABEAN AREA (1000 ha)',
       'SOYABEAN PRODUCTION (1000 tons)', 'SOYABEAN YIELD (Kg per ha)',
       'OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)',
       'OILSEEDS YIELD (Kg per ha)', 'SUGARCANE AREA (1000 ha)',
       'SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)',
       'COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)',
       'COTTON YIELD (Kg per ha)', 'FRUITS AREA (1000 ha)',
       'VEGETABLES AREA (1000 ha)', 'FRUITS AND VEGETABLES AREA (1000 ha)',
       'POTATOES AREA (1000 ha)', 'ONION AREA (1000 ha)',
       'FODDER AREA (1000 ha)'],
      dtype='object')

In [11]:
df.columns = [
    'dist_code', 'year', 'state_code', 'state_name', 'dist_name',
    'rice_area', 'rice_production', 'rice_yield',
    'wheat_area', 'wheat_production', 'wheat_yield',
    'kharif_sorghum_area', 'kharif_sorghum_production', 'kharif_sorghum_yield',
    'rabi_sorghum_area', 'rabi_sorghum_production', 'rabi_sorghum_yield',
    'sorghum_area', 'sorghum_production', 'sorghum_yield',
    'pearl_millet_area', 'pearl_millet_production', 'pearl_millet_yield',
    'maize_area', 'maize_production', 'maize_yield',
    'finger_millet_area', 'finger_millet_production', 'finger_millet_yield',
    'barley_area', 'barley_production', 'barley_yield',
    'chickpea_area', 'chickpea_production', 'chickpea_yield',
    'pigeonpea_area', 'pigeonpea_production', 'pigeonpea_yield',
    'minor_pulses_area', 'minor_pulses_production', 'minor_pulses_yield',
    'groundnut_area', 'groundnut_production', 'groundnut_yield',
    'sesamum_area', 'sesamum_production', 'sesamum_yield',
    'rapeseed_mustard_area', 'rapeseed_mustard_production', 'rapeseed_mustard_yield',
    'safflower_area', 'safflower_production', 'safflower_yield',
    'castor_area', 'castor_production', 'castor_yield',
    'linseed_area', 'linseed_production', 'linseed_yield',
    'sunflower_area', 'sunflower_production', 'sunflower_yield',
    'soyabean_area', 'soyabean_production', 'soyabean_yield',
    'oilseeds_area', 'oilseeds_production', 'oilseeds_yield',
    'sugarcane_area', 'sugarcane_production', 'sugarcane_yield',
    'cotton_area', 'cotton_production', 'cotton_yield',
    'fruits_area', 'vegetables_area', 'fruits_vegetables_area',
    'potatoes_area', 'onion_area', 'fodder_area'
]

In [12]:
#After renameing of the columns
df

,dist_code,year,state_code,state_name,dist_name,rice_area,rice_production,rice_yield,wheat_area,wheat_production,...,sugarcane_yield,cotton_area,cotton_production,cotton_yield,fruits_area,vegetables_area,fruits_vegetables_area,potatoes_area,onion_area,fodder_area
0,1,1966,14,Chhattisgarh,Durg,548.00,185.00,337.59,44.00,20.00,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.00,409.00,747.71,50.00,26.00,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.30,468.00,841.27,53.70,30.00,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.40,400.80,711.40,49.40,26.50,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.60,473.60,828.55,44.20,29.00,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16141,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.00,0.0,0.0,0.0,0.00,9.02,9.03,0.48,0.08,0.00
16142,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.00,0.0,0.0,0.0,0.00,8.63,8.64,0.46,0.04,0.00
16143,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.00,0.0,0.0,0.0,0.00,6.84,6.85,0.42,0.01,0.00
16144,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.00,0.0,0.0,0.0,0.03,6.40,6.43,0.03,0.01,0.00
16145,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00

In [13]:
# drop the columns with all missing values
df.dropna(axis=1, how='all', inplace=True)

In [ ]:
# Use median for numeric columns instead of 0
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna('Unknown', inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

In [17]:
# Columns and their data types

for col, dtype in df.dtypes.items():
    print(f"Column: {col}, Data type: {dtype}")

Column: dist_code, Data type: int64
Column: year, Data type: int64
Column: state_code, Data type: int64
Column: state_name, Data type: object
Column: dist_name, Data type: object
Column: rice_area, Data type: float64
Column: rice_production, Data type: float64
Column: rice_yield, Data type: float64
Column: wheat_area, Data type: float64
Column: wheat_production, Data type: float64
Column: wheat_yield, Data type: float64
Column: kharif_sorghum_area, Data type: float64
Column: kharif_sorghum_production, Data type: float64
Column: kharif_sorghum_yield, Data type: float64
Column: rabi_sorghum_area, Data type: float64
Column: rabi_sorghum_production, Data type: float64
Column: rabi_sorghum_yield, Data type: float64
Column: sorghum_area, Data type: float64
Column: sorghum_production, Data type: float64
Column: sorghum_yield, Data type: float64
Column: pearl_millet_area, Data type: float64
Column: pearl_millet_production, Data type: float64
Column: pearl_millet_yield, Data type: float64
Column: maize_area, Data type: float64
Column: maize_production, Data type: float64
Column: maize_yield, Data type: float64
Column: finger_millet_area, Data type: float64
Column: finger_millet_production, Data type: float64
Column: finger_millet_yield, Data type: float64
Column: barley_area, Data type: float64
Column: barley_production, Data type: float64
Column: barley_yield, Data type: float64
Column: chickpea_area, Data type: float64
Column: chickpea_production, Data type: float64
Column: chickpea_yield, Data type: float64
Column: pigeonpea_area, Data type: float64
Column: pigeonpea_production, Data type: float64
Column: pigeonpea_yield, Data type: float64
Column: minor_pulses_area, Data type: float64
Column: minor_pulses_production, Data type: float64
Column: minor_pulses_yield, Data type: float64
Column: groundnut_area, Data type: float64
Column: groundnut_production, Data type: float64
Column: groundnut_yield, Data type: float64
Column: sesamum_area, Data type: float64
Column: sesamum_production, Data type: float64
Column: sesamum_yield, Data type: float64
Column: rapeseed_mustard_area, Data type: float64
Column: rapeseed_mustard_production, Data type: float64
Column: rapeseed_mustard_yield, Data type: float64
Column: safflower_area, Data type: float64
Column: safflower_production, Data type: float64
Column: safflower_yield, Data type: float64
Column: castor_area, Data type: float64
Column: castor_production, Data type: float64
Column: castor_yield, Data type: float64
Column: linseed_area, Data type: float64
Column: linseed_production, Data type: float64
Column: linseed_yield, Data type: float64
Column: sunflower_area, Data type: float64
Column: sunflower_production, Data type: float64
Column: sunflower_yield, Data type: float64
Column: soyabean_area, Data type: float64
Column: soyabean_production, Data type: float64
Column: soyabean_yield, Data type: float64
Column: oilseeds_area, Data type: float64
Column: oilseeds_production, Data type: float64
Column: oilseeds_yield, Data type: float64
Column: sugarcane_area, Data type: float64
Column: sugarcane_production, Data type: float64
Column: sugarcane_yield, Data type: float64
Column: cotton_area, Data type: float64
Column: cotton_production, Data type: float64
Column: cotton_yield, Data type: float64
Column: fruits_area, Data type: float64
Column: vegetables_area, Data type: float64
Column: fruits_vegetables_area, Data type: float64
Column: potatoes_area, Data type: float64
Column: onion_area, Data type: float64
Column: fodder_area, Data type: float64

In [18]:
# Save Cleaned file

df.to_csv('cleaned_agriculture_data.csv', index=False)

In [7]:
print(df['OILSEEDS AREA (1000 ha)'])

0         50.70
1        113.55
2        126.62
3        114.14
4        126.40
          ...
16141      1.33
16142      1.27
16143      1.42
16144      0.00
16145      0.00
Name: OILSEEDS AREA (1000 ha), Length: 16146, dtype: float64